import { PlaylistId, Track, RaagInfo } from '../types';

export const EXTERNAL_LINKS = {
  youtubeMusic: 'https://music.youtube.com/playlist?list=PLJAiFJ6bGyew',
  spotify: 'https://open.spotify.com/playlist/1zVKSwcN1UDYBXsBWQlp16?si=-F4hxElZQqiGYqkdMnrgfg&nd=1&dlsi=9058ad3b40b24163',
};

export const TRACK_CATALOG: Track[] = [
  // ==================== BAITHAK (Intimate Instrumental & Vocal Masters) ====================
  {
    id: 'b1',
    title: 'Raag Yaman',
    artist: 'Ustad Rashid Khan',
    raga: 'Raag Yaman',
    gharana: 'Rampur-Sahaswan Gharana',
    duration: '16:30',
    videoId: '9eB3p1Z0vQ0',
    playlistId: 'baithak',
    notes: 'Sublime voice culture breathing pure evening tranquility into Yaman.',
    normalizationGain: 1.0,
  },
  {
    id: 'b2',
    title: 'Raga Bhairavi (Live Baithak)',
    artist: 'Ustad Bismillah Khan',
    raga: 'Raga Bhairavi',
    gharana: 'Banaras Gharana',
    duration: '15:20',
    videoId: 'qC8e1f0L_bE',
    playlistId: 'baithak',
    notes: 'Legendary shehnai recital imbued with soulful Banarasi thumri nuances.',
    normalizationGain: 0.98,
  },
  {
    id: 'b3',
    title: 'Raga Malkauns (Live in Kolkata)',
    artist: 'Pandit Nikhil Banerjee',
    raga: 'Raga Malkauns',
    gharana: 'Maihar Gharana',
    duration: '22:45',
    videoId: 'mD2a4gH-a88',
    playlistId: 'baithak',
    notes: 'Deeply spiritual sitar alaap and gat celebrating nocturnal silence.',
    normalizationGain: 1.0,
  },
  {
    id: 'b4',
    title: 'Raga Bhimpalasi (Vilambit & Drut Khayal)',
    artist: 'Pandit Bhimsen Joshi',
    raga: 'Raga Bhimpalasi',
    gharana: 'Kirana Gharana',
    duration: '24:30',
    videoId: 'h8Lw-s0M8tA',
    playlistId: 'baithak',
    notes: 'Majestic afternoon khayal resonating with devotional fervor.',
    normalizationGain: 0.95,
  },
  {
    id: 'b5',
    title: 'Raga Pilu (Acoustic Sarod Baithak)',
    artist: 'Ustad Ali Akbar Khan',
    raga: 'Raga Pilu',
    gharana: 'Maihar Gharana',
    duration: '19:40',
    videoId: 'Oa_0x9wG-qY',
    playlistId: 'baithak',
    notes: 'Hauntingly emotive sarod melodies woven across vintage rugs.',
    normalizationGain: 1.0,
  },
  {
    id: 'b6',
    title: 'Bageshree (Evening Mehfil)',
    artist: 'Pandit Hariprasad Chaurasia',
    raga: 'Raga Bageshri',
    gharana: 'Maihar Gharana',
    duration: '21:15',
    videoId: 'u_1BwP4a2_o',
    playlistId: 'baithak',
    notes: 'Soothing bamboo flute evoking the gentle yearning of midnight.',
    normalizationGain: 0.98,
  },

  // ==================== RIYAZ (Contemplative Morning & Long-Form Alaap) ====================
  {
    id: 'r1',
    title: 'Raga Ahir Bhairav (Morning Santoor)',
    artist: 'Pandit Shivkumar Sharma',
    raga: 'Raga Ahir Bhairav',
    gharana: 'Kashmir Tradition',
    duration: '26:50',
    videoId: '4pE3v0G7b8Q',
    playlistId: 'riyaz',
    notes: 'Crystal clear acoustic raindrops awakening the morning dawn.',
    normalizationGain: 1.0,
  },
  {
    id: 'r2',
    title: 'Raga Todi (Detailed Sitar Alaap & Jod)',
    artist: 'Ustad Shahid Parvez',
    raga: 'Raga Todi',
    gharana: 'Etawah / Imdadkhani',
    duration: '31:20',
    videoId: 'kE6d9yV_a7A',
    playlistId: 'riyaz',
    notes: 'Austerity and profound introspection in the classical morning canon.',
    normalizationGain: 0.96,
  },
  {
    id: 'r3',
    title: 'Raga Darbari Kanada (Rudra Veena Alaap)',
    artist: 'Ustad Asad Ali Khan',
    raga: 'Raga Darbari Kanada',
    gharana: 'Khandarbani Dhrupad',
    duration: '28:10',
    videoId: '0gQ_u5Vq9o8',
    playlistId: 'riyaz',
    notes: 'Ancient microtonal andolans on the majestic Rudra Veena.',
    normalizationGain: 1.0,
  },
  {
    id: 'r4',
    title: 'Raga Bhoopali (Vilambit Ektaal Khayal)',
    artist: 'Vidushi Kishori Amonkar',
    raga: 'Raga Bhoopali',
    gharana: 'Jaipur-Atrauli Gharana',
    duration: '27:40',
    videoId: '2pW8m9_bXp0',
    playlistId: 'riyaz',
    notes: 'Luminous vocal expression exploring emotional bhakti.',
    normalizationGain: 0.97,
  },

  // ==================== MEHFIL (Nocturnal Gatherings & Thumri) ====================
  {
    id: 'm1',
    title: 'Ras Ke Bhare Tore Nain (Thumri)',
    artist: 'Girija Devi',
    raga: 'Mishra Bhairavi',
    gharana: 'Banaras Gharana',
    duration: '09:20',
    videoId: 'f9N2q4bZ_8w',
    playlistId: 'mehfil',
    notes: 'Sensuous and tender Poorab Ang thumri by the Appaji of Banaras.',
    normalizationGain: 0.95,
  },
  {
    id: 'm2',
    title: 'Deewana Banana Hai To Deewana Bana De',
    artist: 'Begum Akhtar',
    raga: 'Dadra / Ghazal',
    gharana: 'Lucknow / Patiala',
    duration: '06:45',
    videoId: 'e9K3pW1yZ8E',
    playlistId: 'mehfil',
    notes: 'The immortal Mallika-e-Ghazal capturing the fragrance of courtly baithaks.',
    normalizationGain: 0.95,
  },
  {
    id: 'm3',
    title: 'Yaad Piya Ki Aaye (Thumri)',
    artist: 'Ustad Bade Ghulam Ali Khan',
    raga: 'Thumri in Bhinna Shadja',
    gharana: 'Patiala Gharana',
    duration: '07:55',
    videoId: '1qP3a4oX_Y0',
    playlistId: 'mehfil',
    notes: 'Unrivaled vocal ornamentations and nostalgic longing.',
    normalizationGain: 0.96,
  },
  {
    id: 'm4',
    title: 'Raga Bihag (Midnight Mehfil Khayal)',
    artist: 'Pandit Jasraj',
    raga: 'Raga Bihag',
    gharana: 'Mewati Gharana',
    duration: '22:10',
    videoId: 'k8N3v0m9L_A',
    playlistId: 'mehfil',
    notes: 'Silken romanticism in the heart of midnight.',
    normalizationGain: 0.98,
  },
];

export const RAAG_CATALOG: RaagInfo[] = [
  {
    name: 'Raag Yaman',
    timeOfDay: 'First prahar of the night (Pratham Prahar)',
    thaat: 'Kalyan',
    mood: 'Devotional, peaceful, serene, romantic (Shringara & Shanta)',
    tracks: ['b1'],
  },
  {
    name: 'Raga Bhairavi',
    timeOfDay: 'Early morning / Universal concluding raga',
    thaat: 'Bhairavi',
    mood: 'Compassion, yearning, pathos, poignant farewell (Karuna)',
    tracks: ['b2', 'm1'],
  },
  {
    name: 'Raga Malkauns',
    timeOfDay: 'Deep midnight (Tritiya Prahar)',
    thaat: 'Bhairavi',
    mood: 'Profound solemnity, meditative calm, spiritual gravity',
    tracks: ['b3'],
  },
  {
    name: 'Raga Bhimpalasi',
    timeOfDay: 'Late afternoon (Triteeya Prahar)',
    thaat: 'Kafi',
    mood: 'Passionate longing, tender devotion, melancholic beauty',
    tracks: ['b4'],
  },
  {
    name: 'Raga Pilu',
    timeOfDay: 'Late afternoon to evening',
    thaat: 'Kafi',
    mood: 'Light classical, romantic charm, wistful thumri mood',
    tracks: ['b5'],
  },
  {
    name: 'Raga Bageshri',
    timeOfDay: 'Midnight (Madhyaratri)',
    thaat: 'Kafi',
    mood: 'Romantic anticipation, sweet sorrow of separation (Viraha)',
    tracks: ['b6'],
  },
  {
    name: 'Raga Ahir Bhairav',
    timeOfDay: 'Daybreak / Early morning (Pratham Prahar)',
    thaat: 'Bhairav',
    mood: 'Quiet contemplation, renewal, spiritual dawn (Bhakti)',
    tracks: ['r1'],
  },
  {
    name: 'Raga Todi',
    timeOfDay: 'Late morning (Dvitiya Prahar)',
    thaat: 'Todi',
    mood: 'Profound pathos, austere asceticism, intense yearning',
    tracks: ['r2'],
  },
  {
    name: 'Raga Darbari Kanada',
    timeOfDay: 'Midnight (Nisheeth)',
    thaat: 'Asavari',
    mood: 'Royal grandeur, nocturnal gravity, profound philosophical depth',
    tracks: ['r3'],
  },
  {
    name: 'Raga Bhoopali',
    timeOfDay: 'First prahar of the night (Evening twilight)',
    thaat: 'Kalyan',
    mood: 'Joyful calm, innocence, serene majesty (Shanta & Veera)',
    tracks: ['r4'],
  },
  {
    name: 'Raga Bihag',
    timeOfDay: 'Second prahar of the night (10 PM – Midnight)',
    thaat: 'Bilawal',
    mood: 'Sensuous, gentle celebration, aristocratic midnight joy',
    tracks: ['m4'],
  },
];

export function getTracksByPlaylist(playlistId: PlaylistId): Track[] {
  return TRACK_CATALOG.filter((t) => t.playlistId === playlistId);
}

